#define NUM_OF_TILES 7
/*MISC TILES */
#define PLAYER_GFX "P"
#define PLAYER_COLOR MAGENTA
#define PLAYER_VISIBLE 1
#define PLAYER_CATEGORY CATEGORY_PLAYER
//
#define GRASS_GFX ","
#define GRASS_COLOR GREEN
#define GRASS_VISIBLE 1
#define GRASS_CATEGORY CATEGORY_NONE
/*ROOM TILES*/
#define VERTICAL_DOOR_GFX "&"
#define VERTICAL_DOOR_COLOR WHITE
#define VERTICAL_DOOR_VISIBLE 1
#define VERTICAL_DOOR_CATEGORY CATEGORY_ROOM
//
#define HORIZONTAL_DOOR_GFX "&"
#define HORIZONTAL_DOOR_COLOR WHITE
#define HORIZONTAL_DOOR_VISIBLE 1
#define HORIZONTAL_DOOR_CATEGORY CATEGORY_ROOM
//
#define CORNER_GFX "#"
#define CORNER_COLOR YELLOW
#define CORNER_VISIBLE 1
#define CORNER_CATEGORY CATEGORY_ROOM
//
#define WALL_GFX "#"
#define WALL_COLOR YELLOW
#define WALL_VISIBLE 1
#define WALL_CATEGORY CATEGORY_ROOM
//
#define FLOOR_GFX "_"
#define FLOOR_COLOR YELLOW
#define FLOOR_VISIBLE 1
#define FLOOR_CATEGORY CATEGORY_ROOM
/**/
